// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrL5I7NOQ0BqcwIUUo7_y35lFH5lzD7K8',
    appId: '1:266972012359:web:08be4bc25d16e7c8667662',
    messagingSenderId: '266972012359',
    projectId: 'presensi-app-d9e2c',
    authDomain: 'presensi-app-d9e2c.firebaseapp.com',
    databaseURL:
        'https://presensi-app-d9e2c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'presensi-app-d9e2c.firebasestorage.app',
    measurementId: 'G-52H6Z31YDB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRBhiUd0Umt3DMdgf3orcsbLD7-W4A1t0',
    appId: '1:266972012359:android:afc5a01352d8b555667662',
    messagingSenderId: '266972012359',
    projectId: 'presensi-app-d9e2c',
    databaseURL:
        'https://presensi-app-d9e2c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'presensi-app-d9e2c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqIS6H6Z3U4h00YzLSqyW7875-SBsYHW0',
    appId: '1:266972012359:ios:00acd85c6b846e16667662',
    messagingSenderId: '266972012359',
    projectId: 'presensi-app-d9e2c',
    databaseURL:
        'https://presensi-app-d9e2c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'presensi-app-d9e2c.firebasestorage.app',
    iosBundleId: 'com.qms.presensi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqIS6H6Z3U4h00YzLSqyW7875-SBsYHW0',
    appId: '1:266972012359:ios:00acd85c6b846e16667662',
    messagingSenderId: '266972012359',
    projectId: 'presensi-app-d9e2c',
    databaseURL:
        'https://presensi-app-d9e2c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'presensi-app-d9e2c.firebasestorage.app',
    iosBundleId: 'com.qms.presensi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrL5I7NOQ0BqcwIUUo7_y35lFH5lzD7K8',
    appId: '1:266972012359:web:4997b91eb5c72fa3667662',
    messagingSenderId: '266972012359',
    projectId: 'presensi-app-d9e2c',
    authDomain: 'presensi-app-d9e2c.firebaseapp.com',
    databaseURL:
        'https://presensi-app-d9e2c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'presensi-app-d9e2c.firebasestorage.app',
    measurementId: 'G-X5EMCYFBMY',
  );
}
